services:
  - type: web
    name: god-mis-serve
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: godmis-db
          property: connectionString
      - key: JWT_SECRET
        value: godmis123!@#
      - key: YIYAN_ACCESS_TOKEN
        value: test

databases:
  - name: godmis-db
    plan: free
